default:
  - override hydra/output: local
  - override hydra/launcher: local

# general inputs
env: myosuite-v1 # placeholder name, not a real env
algorithm: "SAC"
num_cpu: 32
job_name: "sb3_sac"
n_steps: 128
model_path: None
policy: "MlpPolicy"
train_freq: 1
gradient_steps: 4
batch_size: 1024
policy_kwargs: "dict(net_arch=[64, 64])"
